server:
  port: 8096

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trueclub
    username: root
    password: Lndixit@107
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: TrueClub_Backend